CREATE TABLE IF NOT EXISTS BIBLIOTECA (
    ID_BIBLIOTECA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_BIBLIOTECA VARCHAR(255) NOT NULL,
    DIRECCION_BIBLIOTECA VARCHAR(255),
    TELEFONO_BIBLIOTECA VARCHAR(15),
    PRIMARY KEY (ID_BIBLIOTECA)
);

CREATE TABLE IF NOT EXISTS TIPO_USUARIO(
    ID_TIPO_USUARIO TINYINT NOT NULL AUTO_INCREMENT,
    TIPO_USUARIO VARCHAR(50),
    DESCRIPCION_TIPO_USUARIO VARCHAR (255),
    PRIMARY KEY (ID_TIPO_USUARIO)
);

CREATE TABLE IF NOT EXISTS PAISES(
    CODIGO_PAIS INT NOT NULL,
    CODIGO_ISO3_PAIS VARCHAR(3),
    NOMBRE_PAIS VARCHAR(50),
    GENTILICIO_PAIS VARCHAR(50),
    PRIMARY KEY (CODIGO_PAIS)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR (255) NOT NULL,
    CORREO_USUARIO VARCHAR (255) NOT NULL,
    TELEFONO_USUARIO VARCHAR (15),
    RUT_USUARIO VARCHAR (10),
    CODIGO_PAIS INT,
    HABILITADO TINYINT NOT NULL,
    ID_TIPO_USUARIO TINYINT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_PAIS_USUARIO FOREIGN KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS),
    CONSTRAINT FK_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
);

CREATE TABLE IF NOT EXISTS AUTOR(
    ID_AUTOR INT NOT NULL AUTO_INCREMENT,
    NOMBRE_AUTOR VARCHAR(255),
    SEUDONIMO_AUTOR VARCHAR(50),
    CODIGO_PAIS INT,
    FECHA_NACIMIENTO DATE,
    FECHA_DEFUNCION DATE,
    BIOGRAFIA_AUTOR TEXT,
    FOTO_AUTOR BLOB,
    PRIMARY KEY (ID_AUTOR),
    CONSTRAINT FK_PAIS_AUTOR FOREIGN KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
);

CREATE TABLE IF NOT EXISTS LIBRO(
    ISBN VARCHAR(13) NOT NULL,
    TITULO VARCHAR(255),
    ID_AUTOR INT,
    PRIMARY KEY (ISBN),
    CONSTRAINT FK_AUTOR_LIBRO FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);

CREATE TABLE IF NOT EXISTS TIPO_CATEGORIA(
    ID_TIPO_CATEGORIA TINYINT NOT NULL AUTO_INCREMENT,
    TIPO_CATEGORIA VARCHAR(50),
    PRIMARY KEY (ID_TIPO_CATEGORIA)
    );

CREATE TABLE IF NOT EXISTS CATEGORIA_LIBRO(
    ID_CATEGORIA_LIBRO INT NOT NULL AUTO_INCREMENT,
    ID_TIPO_CATEGORIA TINYINT NOT NULL,
    CATEGORIA_LIBRO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(155),
    PRIMARY KEY (ID_CATEGORIA_LIBRO),
    CONSTRAINT FK_TIPO_CATEOGRIA FOREIGN KEY (ID_TIPO_CATEGORIA) REFERENCES TIPO_CATEGORIA(ID_TIPO_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS EDITORIAL(
    ID_EDITORIAL INT NOT NULL AUTO_INCREMENT,
    NOMBRE_EDITORIAL VARCHAR(255),
    FECHA_FUNDACION DATE,
    CODIGO_PAIS INT,
    TELEFONO_CONTACTO VARCHAR(15),
    CORREO_ELECTRONICO VARCHAR(155),
    PRIMARY KEY (ID_EDITORIAL),
    CONSTRAINT FK_PAIS_EDITORIAL FOREIGN KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
);

CREATE TABLE IF NOT EXISTS DETALLE_LIBRO(
    ID_DETALLE_LIBRO INT NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(13) NOT NULL,
    FECHA_EDICION DATE,
    ID_EDITORIAL INT NOT NULL,
    NUMERO_PAGINAS SMALLINT NOT NULL,
    ID_CATEGORIA_LIBRO VARCHAR(255),
    CANTIDAD_EJEMPLARES SMALLINT NOT NULL,
    EJEMPLARES_DISPONIBLES SMALLINT NOT NULL,
    PRIMARY KEY (ID_DETALLE_LIBRO),
    CONSTRAINT FK_ISBN_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
    CONSTRAINT FK_ID_EDITORIAL_LIBRO FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL(ID_EDITORIAL)
);

CREATE TABLE IF NOT EXISTS PRESTAMO(
    ID_PRESTAMO INT NOT NULL AUTO_INCREMENT,
    ID_DETALLE_LIBRO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_PRESTAMO DATETIME NOT NULL,
    FECHA_DEVOLUCION DATETIME NOT NULL,
    FECHA_DEVUELTO DATETIME,
    CANTIDAD_SOLICITADA TINYINT,
    PRIMARY KEY (ID_PRESTAMO),
    CONSTRAINT FK_DETALLE_LIBRO_PRESTAMO FOREIGN KEY (ID_DETALLE_LIBRO) REFERENCES DETALLE_LIBRO(ID_DETALLE_LIBRO),
    CONSTRAINT FK_USUARIO_PRESTAMO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);